### ISSUE TITLE
Hi, how I can install this, with cmake? 

### ISSUE THREAD

**Issue by FPSychotic** [huningxin/depthsense#1]

**Comment by FPSychotic** [comment]
Is this the depthsense SDK,? for gesture cameras? thank you and sorry by revive this

**Comment by PaintOnBrush** [comment]
looks like it is the older 1.4.5

there's a lot of obsolescence  that needs updating. i found a newer version 1.9 i'm hosting on my github

**Comment by FPSychotic** [comment]
> looks like it is the older 1.4.5
> 
> there's a lot of obsolescence that needs updating. i found a newer version 1.9 i'm hosting on my github
Thanks, take care,.I sold the camera but O will give the info to the new owner.
